# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8d936adc61c786148d10adbe516e69c1b5d46d4419b6cd5917260dc976684f31d1e80e01526272760c85eae90790d91fc801d97087cea71effabf2594f5af8f

test:
  secret_key_base: f5e8d1666fde4fc200d189fbd5d98aa433e7c8131412fec2267a179bc3da14dcf75c8f94c5177c3c6ab160360993ed1b3704d76e405607dcb4bdb4e2f3ed0f11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
